kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: config-volume
